baseurl = "https://spesch.github.io/"
title = "Hochzeit"
author = "Georg Sperl"
paginate = 3
theme = "arabica"

[params]
    description = "Georg & Uschi"
    dateFormatToUse = "2006-01-02"
    replaceGoogleFonts = "fonts.loli.net"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true